# -*- coding: utf-8 -*-
"""Untitled15.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1w2XdAH5aZWXR2IcaEEzoLvb0MkT0UAic
"""

import pandas as pd
from statsmodels.tsa.holtwinters import ExponentialSmoothing

# Read data from the "sales_data.xls" file
df = pd.read_csv("sales_data.csv")

# Convert the "Order Date" column to a datetime index

# Create a time series object from the "Sales" column
df.index = pd.to_datetime(df["Order Date"])
# Fit the double exponential smoothing model
df = df[df['Category'] == 'Furniture']
ts = df["Sales"].resample("M").sum()/30

# model_double = ExponentialSmoothing(ts, trend="add")
# model_double_fit = model_double.fit(smoothing_level=1, smoothing_slope=0.01, optimized=False)

# # Predict the future values
# pred_double = model_double_fit.predict(start=ts.index[-1], end=ts.index[-1] + pd.DateOffset(weeks=100))

# Fit the triple exponential smoothing model
model_triple = ExponentialSmoothing(ts, trend="add", seasonal="add", seasonal_periods=24)
model_triple_fit = model_triple.fit(smoothing_level=0.2, smoothing_slope=0.1, smoothing_seasonal=0.1, optimized=False)

# Predict the future values
pred_triple = model_triple_fit.predict(start=ts.index[-12], end=ts.index[-1] )
import matplotlib.pyplot as plt


   
    # Generate the plot
import matplotlib.pyplot as plt
import numpy as np
mse = ((pred_triple - ts) ** 2).mean()
rmse = mse ** 0.5
mape = (abs(pred_triple - ts) / ts).mean()
# plt.text("MSE: ", mse)
# plt.text("RMSE: ", rmse)
# plt.text("MAPE: ", mape)

plt.plot(ts.index, ts, label="Observed")
plt.plot(pred_triple.index, pred_triple, label="Triple ES Prediction")
plt.legend(loc="upper left")
plt.xlabel("MSE: "+ str(mse)+ " RMSE: "+str(rmse)+ " MAPE: "+ str(mape))
plt.show()
import matplotlib.pyplot as plt