# -*- coding: utf-8 -*-
"""Untitled16.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1n7WB8acTAyOB8-rJ76twpXpHJp9M8wHY
"""

# Import necessary libraries
from statsmodels.tsa.seasonal import seasonal_decompose
import matplotlib.pyplot as plt
import pandas as pd

# Load the dataset
df = pd.read_csv("sales_data.csv")

# Select only the rows for the furniture category
df = df[df["Category"] == "Furniture"]

# Convert the Order Date column to a datetime data type and set it as the index of the DataFrame
df["Order Date"] = pd.to_datetime(df["Order Date"])
df.set_index("Order Date", inplace=True)

# Resample the data to a monthly frequency, taking the sum of all daily sales values in each month
monthly_sales = (df["Sales"].resample("M").sum())/30

# Perform the decomposition
result = seasonal_decompose(monthly_sales, model='additive')

# Extract the trend, seasonal, and residual components
trend = result.trend
seasonal = result.seasonal
residual = result.resid

# Plot the decomposition
plt.figure()
plt.subplot(4,1,1)
plt.plot(monthly_sales, label='Original')
plt.legend(loc='best')
plt.subplot(4,1,2)
plt.plot(trend, label='Trend')
plt.legend(loc='best')
plt.subplot(4,1,3)
plt.plot(seasonal,label='Seasonality')
plt.legend(loc='best')
plt.subplot(4,1,4)
plt.plot(residual, label='Residuals')
plt.legend(loc='best')
plt.tight_layout()
plt.show()